package com.csye6225.fall2018.courseservice3.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Registrar")
public class Registrar {
	String registrationId;
	String offeringId;
	String offeringType;
	String department;
	int perUnitPrice;

	@DynamoDBHashKey(attributeName = "registrationId")
	@DynamoDBAutoGeneratedKey
	public String getRegistrationId() {
		return registrationId;
	}
	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}
	@DynamoDBAttribute(attributeName = "offeringId")
	public String getOfferingId() {
		return offeringId;
	}
	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}
	@DynamoDBAttribute(attributeName = "offeringType")
	public String getOfferingType() {
		return offeringType;
	}
	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
	}
	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	@DynamoDBAttribute(attributeName = "perUnitPrice")
	public int getPerUnitPrice() {
		return perUnitPrice;
	}
	public void setPerUnitPrice(int perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}
}
